// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *App → Main Navigation*
 */
export interface AppDocumentDataMainNavigationItem {
  /**
   * Link field in *App → Main Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app.main_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for App documents
 */
interface AppDocumentData {
  /**
   * Main Navigation field in *App*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: app.main_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_navigation: prismic.GroupField<
    Simplify<AppDocumentDataMainNavigationItem>
  > /**
   * Footer Text field in *App*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: app.footer_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  footer_text: prismic.KeyTextField;

  /**
   * Phone field in *App*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app.phone
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  phone: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Mail field in *App*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: app.mail
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  mail: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * App document from Prismic
 *
 * - **API ID**: `app`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AppDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AppDocumentData>, "app", Lang>;

/**
 * Item in *Box → Links*
 */
export interface BoxDocumentDataLinksItem {
  /**
   * Link field in *Box → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: box.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Box documents
 */
interface BoxDocumentData {
  /**
   * Title field in *Box*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: box.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Period field in *Box*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: box.period
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  period: prismic.KeyTextField;

  /**
   * Links field in *Box*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: box.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<BoxDocumentDataLinksItem>>;

  /**
   * Position field in *Box*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: box.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position: prismic.KeyTextField;

  /**
   * Text field in *Box*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: box.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Box document from Prismic
 *
 * - **API ID**: `box`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BoxDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BoxDocumentData>, "box", Lang>;

type PageDefaultDocumentDataSlicesSlice = PageHeaderSlice;

/**
 * Content for Page: Default documents
 */
interface PageDefaultDocumentData {
  /**
   * Title field in *Page: Default*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_default.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page: Default*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_default.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDefaultDocumentDataSlicesSlice> /**
   * Meta Title field in *Page: Default*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page_default.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page: Default*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page_default.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page: Default*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_default.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page: Default document from Prismic
 *
 * - **API ID**: `page_default`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDefaultDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PageDefaultDocumentData>,
    "page_default",
    Lang
  >;

type PageHomeDocumentDataSlicesSlice =
  | WorkExperienceSlice
  | ScrollingTextSlice
  | MarqueeWrapperSlice
  | ProjectsSlice
  | PageHeaderSlice;

/**
 * Content for Page: Home documents
 */
interface PageHomeDocumentData {
  /**
   * Title field in *Page: Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page: Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Page: Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page: Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page: Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page: Home document from Prismic
 *
 * - **API ID**: `page_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PageHomeDocumentData>,
    "page_home",
    Lang
  >;

export type AllDocumentTypes =
  | AppDocument
  | BoxDocument
  | PageDefaultDocument
  | PageHomeDocument;

/**
 * Item in *MarqueeWrapper → LogoMarquee → Primary → Items*
 */
export interface MarqueeWrapperSliceLogoMarqueePrimaryItemsItem {
  /**
   * Image field in *MarqueeWrapper → LogoMarquee → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_wrapper.logoMarquee.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *MarqueeWrapper → Default → Primary*
 */
export interface MarqueeWrapperSliceDefaultPrimary {
  /**
   * Title field in *MarqueeWrapper → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_wrapper.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *MarqueeWrapper → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_wrapper.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Reversed field in *MarqueeWrapper → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee_wrapper.default.primary.reversed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reversed: prismic.BooleanField;
}

/**
 * Default variation for MarqueeWrapper Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeWrapperSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeWrapperSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MarqueeWrapper → LogoMarquee → Primary*
 */
export interface MarqueeWrapperSliceLogoMarqueePrimary {
  /**
   * Title field in *MarqueeWrapper → LogoMarquee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_wrapper.logoMarquee.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *MarqueeWrapper → LogoMarquee → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_wrapper.logoMarquee.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<MarqueeWrapperSliceLogoMarqueePrimaryItemsItem>
  >;

  /**
   * Reversed field in *MarqueeWrapper → LogoMarquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee_wrapper.logoMarquee.primary.reversed
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reversed: prismic.BooleanField;
}

/**
 * LogoMarquee variation for MarqueeWrapper Slice
 *
 * - **API ID**: `logoMarquee`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeWrapperSliceLogoMarquee = prismic.SharedSliceVariation<
  "logoMarquee",
  Simplify<MarqueeWrapperSliceLogoMarqueePrimary>,
  never
>;

/**
 * Slice variation for *MarqueeWrapper*
 */
type MarqueeWrapperSliceVariation =
  | MarqueeWrapperSliceDefault
  | MarqueeWrapperSliceLogoMarquee;

/**
 * MarqueeWrapper Shared Slice
 *
 * - **API ID**: `marquee_wrapper`
 * - **Description**: MarqueeWrapper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeWrapperSlice = prismic.SharedSlice<
  "marquee_wrapper",
  MarqueeWrapperSliceVariation
>;

/**
 * Primary content in *PageHeader → Default → Primary*
 */
export interface PageHeaderSliceDefaultPrimary {
  /**
   * Title field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Caption field in *PageHeader → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_header.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for PageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHeader*
 */
type PageHeaderSliceVariation = PageHeaderSliceDefault;

/**
 * PageHeader Shared Slice
 *
 * - **API ID**: `page_header`
 * - **Description**: PageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeaderSlice = prismic.SharedSlice<
  "page_header",
  PageHeaderSliceVariation
>;

/**
 * Item in *Projects → Default → Primary → Items*
 */
export interface ProjectsSliceDefaultPrimaryItemsItem {
  /**
   * Video field in *Projects → Default → Primary → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.items[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Project Url field in *Projects → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.items[].project_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Tech Stack field in *Projects → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.items[].tech_stack
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tech_stack: prismic.KeyTextField;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
  /**
   * Title field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Caption field in *Projects → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * Text field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Items field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<ProjectsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  "projects",
  ProjectsSliceVariation
>;

/**
 * Primary content in *ScrollingText → Default → Primary*
 */
export interface ScrollingTextSliceDefaultPrimary {
  /**
   * Text field in *ScrollingText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: scrolling_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for ScrollingText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollingTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScrollingTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScrollingText*
 */
type ScrollingTextSliceVariation = ScrollingTextSliceDefault;

/**
 * ScrollingText Shared Slice
 *
 * - **API ID**: `scrolling_text`
 * - **Description**: ScrollingText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScrollingTextSlice = prismic.SharedSlice<
  "scrolling_text",
  ScrollingTextSliceVariation
>;

/**
 * Item in *WorkExperience → Default → Primary → Items*
 */
export interface WorkExperienceSliceDefaultPrimaryItemsItem {
  /**
   * Item field in *WorkExperience → Default → Primary → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: work_experience.default.primary.items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"box">;
}

/**
 * Primary content in *WorkExperience → Default → Primary*
 */
export interface WorkExperienceSliceDefaultPrimary {
  /**
   * Title field in *WorkExperience → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_experience.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Items field in *WorkExperience → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_experience.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<WorkExperienceSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for WorkExperience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkExperienceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkExperience*
 */
type WorkExperienceSliceVariation = WorkExperienceSliceDefault;

/**
 * WorkExperience Shared Slice
 *
 * - **API ID**: `work_experience`
 * - **Description**: WorkExperience
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkExperienceSlice = prismic.SharedSlice<
  "work_experience",
  WorkExperienceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AppDocument,
      AppDocumentData,
      AppDocumentDataMainNavigationItem,
      BoxDocument,
      BoxDocumentData,
      BoxDocumentDataLinksItem,
      PageDefaultDocument,
      PageDefaultDocumentData,
      PageDefaultDocumentDataSlicesSlice,
      PageHomeDocument,
      PageHomeDocumentData,
      PageHomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      MarqueeWrapperSlice,
      MarqueeWrapperSliceDefaultPrimary,
      MarqueeWrapperSliceLogoMarqueePrimaryItemsItem,
      MarqueeWrapperSliceLogoMarqueePrimary,
      MarqueeWrapperSliceVariation,
      MarqueeWrapperSliceDefault,
      MarqueeWrapperSliceLogoMarquee,
      PageHeaderSlice,
      PageHeaderSliceDefaultPrimary,
      PageHeaderSliceVariation,
      PageHeaderSliceDefault,
      ProjectsSlice,
      ProjectsSliceDefaultPrimaryItemsItem,
      ProjectsSliceDefaultPrimary,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
      ScrollingTextSlice,
      ScrollingTextSliceDefaultPrimary,
      ScrollingTextSliceVariation,
      ScrollingTextSliceDefault,
      WorkExperienceSlice,
      WorkExperienceSliceDefaultPrimaryItemsItem,
      WorkExperienceSliceDefaultPrimary,
      WorkExperienceSliceVariation,
      WorkExperienceSliceDefault,
    };
  }
}
