// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  marquee_wrapper: defineAsyncComponent(
    () => import("./MarqueeWrapper/index.vue"),
  ),
  page_header: defineAsyncComponent(() => import("./PageHeader/index.vue")),
  projects: defineAsyncComponent(() => import("./Projects/index.vue")),
  scrolling_text: defineAsyncComponent(
    () => import("./ScrollingText/index.vue"),
  ),
  work_experience: defineAsyncComponent(
    () => import("./WorkExperience/index.vue"),
  ),
});
